kind: Deployment
apiVersion: apps/v1
metadata:
   name: pkstiyara
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: pkstiyara
   template:
      metadata:
        labels:
          app: pkstiyara
      spec:
       containers:
        - name: pkstiyara
          image: pkstiyara/demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80